<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Pet>
 */
class PetFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = \App\Models\Pet::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $petNames = [
            "Luna",
            "Max",
            "Bella",
            "Rocky",
            "Coco",
            "Nala",
            "Bruno",
            "Lola",
            "Milo",
            "Kira",
            "Toby",
            "Sasha",
            "Zeus",
            "Maya",
            "Jack",
            "Canela",
            "Mía",
            "Oliver",
            "Simba",
            "Princesa",
            "Mateo",
            "Sofía",
            "Lucas",
            "Valentina",
            "Chispas",
            "Firulais",
            "Doki",
            "Ringo",
            "Trufa",
            "Sol",
            "Rayo",
            "Estrella",
            "Buñuelo",
            "Tinto",
            "Arepa",
            "Guaro",
            "Sancocho",
            "Rogelio",
            "Matilde",
            "Macondo",
            "Chocoramo",
            "Pacho",
            "Bolillo",
            "Pelusa",
            "Pecas",
            "Manchitas",
            "Copito",
            "Pipa",
            "Osito",
            "Gordis",
            "Dulce",
            "Cachetes",
            "Peque",
            "Bolita",
            "Thor",
            "Atenea",
            "Odín",
            "Homero",
            "Frida",
            "Baloo",
            "Dory",
            "Rambo",
            "Fiona",
            "Hércules",
            "Venus",
            "Aquiles",
            "Bart",
            "Leia",
            "Arya",
            "Neo",
            "Nerón",
            "Kenia",
            "Zara",
            "Nina",
            "Rex",
            "Leo",
            "Gus",
            "Benji",
            "Mila",
            "Kai",
            "Enzo",
            "Duquesa",
            "Marqués",
            "Sultán",
            "Valiente",
            "Bandido",
            "Duna",
            "Jade",
            "Lulú",
            "Kenay",
            "Chispi",
            "Pacha",
            "Pili",
            "Chavo",
            "Tita",
            "Tito",
            "Sam",
            "Kimba",
            "Ronco",
            "Cielo"
        ];
        $razasColombia = [
            'Criollo Colombiano',
            'Sabueso Colombiano',
            'Labrador Retriever',
            'Golden Retriever',
            'Pastor Alemán',
            'Bulldog Francés',
            'Pitbull Terrier',
            'American Bully',
            'Beagle',
            'Rottweiler',
            'Shih Tzu',
            'Poodle',
            'Chihuahua',
            'Boxer',
            'Cocker Spaniel',
            'Doberman',
            'Husky Siberiano',
            'Border Collie',
            'Dálmata',
            'Pinscher Miniatura',
            'Bóxer Colombiano',
            'Maltés',
            'Boston Terrier',
            'Yorkshire Terrier',
            'Samoyedo',
            'Akita Inu',
            'Basset Hound',
            'Schnauzer',
            'Pug',
            'Gran Danés',
            'Weimaraner',
            'Fox Terrier',
            'Cane Corso',
            'Pastor Belga',
            'Shar Pei',
            'San Bernardo',
            'Bull Terrier',
            'Galgo Español',
            'Bichón Frisé',
            'Criollo de finca',
            'Criollo de montaña',
            'Lobo Siberiano',
            'Dogo Argentino',
            'Terrier Escocés',
            'Pastor Australiano',
            'Husky Colombiano',
            'Criollo costeño',
            'Criollo paisa',
            'Criollo bogotano',
            'Bulldog Inglés'
        ];

        $razasGatosColombia = [
            'Criollo Colombiano',
            'Criollo Bogotano',
            'Criollo Costeño',
            'Criollo Paisa',
            'Angora Turco',
            'Persa',
            'Siamés',
            'Maine Coon',
            'Bengalí',
            'British Shorthair',
            'Oriental',
            'Sphynx',
            'Azul Ruso',
            'Himalayo',
            'Scottish Fold',
            'Ragdoll',
            'Abyssinian',
            'Manx',
            'Savannah',
            'Bombay',
            'Bosque de Noruega',
            'American Shorthair',
            'Exótico de pelo corto',
            'Cornish Rex',
            'Devon Rex',
            'Balinese',
            'Selkirk Rex',
            'Birmano',
            'Chartreux',
            'Tonkinés',
            'Ocicat',
            'Snowshoe',
            'Singapura',
            'Turkish Van',
            'Pixie-Bob',
            'Laperm',
            'Munchkin',
            'Oriental de pelo largo',
            'Burmés',
            'Burmilla',
            'Somalí',
            'Van Turco',
            'Chausie',
            'Peterbald',
            'Korat',
            'Nebelung',
            'Cymric',
            'Toyger',
            'Criollo de finca',
            'Criollo de ciudad'
        ];

        $avesColombia = [
            'Loro Amazónico',
            'Guacamayo Azulamarillo',
            'Guacamayo Rojo',
            'Guacamayo Verde',
            'Cacatúa',
            'Canario',
            'Perico Australiano',
            'Periquito de anteojos',
            'Tucán del Chocó',
            'Cacique Candela',
            'Cotorra Cabeza Azul',
            'Cotorra Montañera',
            'Loro Orejiamarillo',
            'Tángara Multicolor',
            'Torcaza',
            'Paloma Doméstica',
            'Colibrí Esmeralda',
            'Colibrí Pico de Espada',
            'Colibrí Cola de Raqueta',
            'Golondrina',
            'Mirla',
            'Cacique de montaña',
            'Azulejo Común',
            'Carpintero Real',
            'Búho',
            'Lechuza',
            'Gallina Criolla',
            'Gallo de pelea',
            'Pavo Real',
            'Pato Criollo',
            'Gallina de Guinea',
            'Pavo',
            'Cisne Negro',
            'Canario Colombiano',
            'Perico Carisucio',
            'Cardenal Guajiro',
            'Turpial',
            'Mielero Verde',
            'Tángara Azuleja',
            'Gavilán Pollero',
            'Águila Crestada',
            'Buitre de Páramo',
            'Barranquero',
            'Guacharaco',
            'Loro Real Amazónico',
            'Cacatúa Ninfa',
            'Agapornis (inseparable)',
            'Cotora del Caribe',
            'Pijul',
            'Zarapito',
            'Pico de Plata'
        ];

        $conejosColombia = [
            'Conejo Criollo Colombiano',
            'Conejo de Finca',
            'Conejo Neozelandés Blanco',
            'Conejo Californiano',
            'Conejo Rex',
            'Conejo Mini Rex',
            'Conejo Cabeza de León',
            'Conejo Belier (orejas caídas)',
            'Conejo Mini Lop',
            'Conejo Holandés Enano',
            'Conejo Chinchilla',
            'Conejo Gigante de Flandes',
            'Conejo Angora',
            'Conejo Mariposa',
            'Conejo Satinado',
            'Conejo Havana',
            'Conejo Palomino',
            'Conejo Plata',
            'Conejo Tan',
            'Conejo Azul de Viena',
            'Conejo León Miniatura',
            'Conejo Alaska',
            'Conejo Himalayan',
            'Conejo Holandés',
            'Conejo Mini English Lop',
            'Conejo Gigante Continental',
            'Conejo Criollo de Montaña',
            'Conejo Criollo Costeño',
            'Conejo Criollo Paisa',
            'Conejo Rex Colombiano',
            'Conejo Teddy Dwarf',
            'Conejo Dutch',
            'Conejo English Spot',
            'Conejo American Fuzzy Lop',
            'Conejo Jersey Wooly',
            'Conejo Champagne d’Argent',
            'Conejo Silver Marten',
            'Conejo Cinnamon',
            'Conejo Gigante Español',
            'Conejo Havana Colombiano',
            'Conejo Angora Colombiano',
            'Conejo Mini Plush Lop',
            'Conejo American Chinchilla',
            'Conejo Creme dArgent',
            'Conejo Blanc de Hotot',
            'Conejo Lionlop',
            'Conejo Californiano Colombiano',
            'Conejo Mini Satin',
            'Conejo Polish',
            'Conejo Fuzzy Lop',
            'Conejo Criollo de Valle'
        ];

        $kind = fake()->randomElement(['dog', 'cat', 'bird', 'rabbit']);

        switch ($kind) {
            case 'dog':
                $breed = fake()->randomElement($razasColombia);
                break;
            case 'cat':
                $breed = fake()->randomElement($razasGatosColombia);
                break;
            case 'bird':
                $breed = fake()->randomElement($avesColombia);
                break;
            case 'rabbit':
                $breed = fake()->randomElement($conejosColombia);
                break;
            default:
                $breed = 'Unknown';
                break;
        }

        return [
            'name' => fake()->randomElement($petNames),
            'kind' => $kind,
            // weight as a number between 1 and 40 (kg)
            'weight' => fake()->numberBetween(1, 40),
            // age in years between 1 and 15
            'age' => fake()->numberBetween(1, 15),
            'breed' => $breed,
            'location' => fake()->city(),
            'description' => fake()->sentence(8),
        ];
    }
}
